export const NAV_BY_ROLE = {
  admin: [
    { to: "/admin", label: "Dashboard" },
    { to: "/admin/chat", label: "Chat" },
    { to: "/admin/roles", label: "Roles" },
    { to: "/admin/staff", label: "Staff" },
    { to: "/admin/leads", label: "Leads" },
    { to: "/admin/leads-dashboard", label: "Leads Dashboard" },
    { to: "/admin/candidates", label: "Candidates" },
    { to: "/admin/candidates-dashboard", label: "Candidates Dashboard" },
    { to: "/admin/students", label: "Students" },
    { to: "/admin/courses", label: "Courses" },
    { to: "/admin/batches", label: "Batches" },
    { to: "/admin/batch-dashboard", label: "Batch Dashboard" },
    { to: "/admin/daily-followup", label: "Daily Batch Follow-up" },
    { to: "/admin/attendance", label: "Attendance" },
    { to: "/admin/fees", label: "Fees" },
    { to: "/admin/expenses", label: "Expenses" },
    { to: "/admin/profit", label: "Profit & Loss" },
    { to: "/admin/leave", label: "Leave & Permission" },
    { to: "/admin/feedback", label: "Feedback & Complaints" },
    { to: "/admin/notifications", label: "Notifications" },
    { to: "/admin/audit-logs", label: "Audit Logs" },
    { to: "/admin/settings", label: "Settings" },
  ],
  hr: [
    { to: "/hr", label: "Dashboard" },
    { to: "/hr/chat", label: "Chat" },
    { to: "/hr/staff", label: "Staff" },
    { to: "/hr/attendance", label: "Attendance" },
    { to: "/hr/leave", label: "Leave Requests" },
    { to: "/hr/candidates", label: "Candidates" },
    { to: "/hr/candidates-dashboard", label: "Candidates Dashboard" },
    { to: "/hr/students", label: "Students" },
    { to: "/hr/notifications", label: "Notifications" },
  ],
  telecaller: [
    { to: "/telecaller", label: "Dashboard" },
    { to: "/telecaller/chat", label: "Chat" },
    { to: "/telecaller/leads", label: "My Leads" },
    { to: "/telecaller/followups", label: "Today's Follow-ups" },
    { to: "/telecaller/candidates", label: "Candidates" },
    { to: "/telecaller/attendance", label: "Attendance" },
    { to: "/telecaller/leave", label: "Leave & Permission" },
    { to: "/telecaller/notifications", label: "Notifications" },
  ],
  trainer: [
    { to: "/trainer", label: "Dashboard" },
    { to: "/trainer/chat", label: "Chat" },
    { to: "/trainer/batches", label: "My Batches" },
    { to: "/trainer/daily-followup", label: "Daily Batch Follow-up" },
    { to: "/trainer/attendance", label: "Attendance" },
    { to: "/trainer/leave", label: "Leave & Permission" },
    { to: "/trainer/notifications", label: "Notifications" },
  ],
  student: [
    { to: "/student", label: "Dashboard" },
    { to: "/student/course", label: "My Course" },
    { to: "/student/attendance", label: "Attendance" },
    { to: "/student/fees", label: "Fee Details" },
    { to: "/student/documents", label: "My Documents" },
    { to: "/student/leave", label: "Leave" },
    { to: "/student/feedback", label: "Feedback & Complaints" },
    { to: "/student/notifications", label: "Notifications" },
  ],
};
